spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demomo
    username: root
    password: alsl7866!!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVmYq
  expiration: 1800000 # 30분
  refresh-expiration: 1209600000 # 14일